[package]
name = "0x4571/base"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Net = "sleitnick/net@0.2.0"
Promise = "evaera/promise@4.0.0"
Sandwich = "data-oriented-house/sandwich@2.2.2"
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.17.0"

[server-dependencies]
ProfileStore = "2jammers/profilestore@0.1.0"